# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: MPL-2.0
---
- name: Ensure docker registry directories exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ registry_config_dir | trim }}"
    - "{{ registry_binary_target_dir | trim }}"

- name: Copy docker registry binary to registry directory
  shell: cp "{{ additional_executables_destination_path | trim }}/registry" "{{ registry_binary_target_dir | trim }}/registry"
  when: additional_executables_destination_path != registry_binary_target_dir

- name: Copy docker registry config yaml
  template:
    src: "etc/registry/config.yml"
    dest: "{{ registry_config_path | trim }}"
    mode: 0644

- name: Create docker registry systemd service unit
  template:
    src: "etc/systemd/system/docker-registry.service"
    dest: "/etc/systemd/system/docker-registry.service"
    mode: 0644

- name: Enable and start Docker registry service
  systemd:
    name: docker-registry
    enabled: yes
    state: started
    daemon_reload: yes
